# Generated by Django 5.2.5 on 2025-08-31 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Driver_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Vehicle', models.CharField(blank=True, max_length=50, null=True)),
                ('Vehicle_no', models.CharField(blank=True, max_length=30, null=True)),
                ('Availability', models.CharField(blank=True, max_length=40, null=True)),
                ('Contact_no', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HospitalName', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
                ('Contact_no', models.BigIntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=30, null=True)),
                ('Password', models.CharField(blank=True, max_length=40, null=True)),
                ('UserType', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorName', models.CharField(blank=True, max_length=30, null=True)),
                ('Place', models.CharField(blank=True, max_length=40, null=True)),
                ('Department', models.CharField(blank=True, max_length=30, null=True)),
                ('Contact_no', models.IntegerField(blank=True, null=True)),
                ('Photo', models.FileField(blank=True, null=True, upload_to='')),
                ('HOSPITAL', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.hospitalmodel')),
            ],
        ),
        migrations.CreateModel(
            name='BedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomNo', models.IntegerField(blank=True, null=True)),
                ('Availability', models.CharField(blank=True, max_length=30, null=True)),
                ('HOSPITAL', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.hospitalmodel')),
            ],
        ),
        migrations.AddField(
            model_name='hospitalmodel',
            name='LoGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.loginmodel'),
        ),
        migrations.CreateModel(
            name='PharmacyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PharmacyName', models.CharField(blank=True, max_length=40, null=True)),
                ('ContactNo', models.BigIntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=40, null=True)),
                ('Email', models.CharField(blank=True, max_length=40, null=True)),
                ('LOGIN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.loginmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyEquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('MedicineName', models.CharField(blank=True, max_length=30, null=True)),
                ('ManufacturingDate', models.DateField(blank=True, null=True)),
                ('ExpiryDate', models.DateField(blank=True, null=True)),
                ('MedicineDescription', models.CharField(blank=True, max_length=50, null=True)),
                ('MEDICINE', models.IntegerField(blank=True, null=True)),
                ('Photo', models.FileField(blank=True, null=True, upload_to='')),
                ('PHARMACY', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.pharmacymodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Dob', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=40, null=True)),
                ('MedicalHistory', models.CharField(blank=True, max_length=40, null=True)),
                ('Email', models.CharField(blank=True, max_length=40, null=True)),
                ('Address', models.CharField(blank=True, max_length=40, null=True)),
                ('Contact_no', models.BigIntegerField(blank=True, null=True)),
                ('Photo', models.FileField(blank=True, null=True, upload_to='userprofile/')),
                ('LOGIN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.loginmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True, null=True)),
                ('Review', models.CharField(blank=True, max_length=300, null=True)),
                ('Rating', models.FloatField(blank=True, null=True)),
                ('USER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True, null=True)),
                ('Complaint', models.CharField(max_length=50)),
                ('Reply', models.CharField(max_length=50)),
                ('USER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='BedBookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('BED', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.bedmodel')),
                ('USER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.IntegerField(blank=True, null=True)),
                ('Token', models.IntegerField(blank=True, null=True)),
                ('Issue', models.CharField(blank=True, max_length=50, null=True)),
                ('Status', models.CharField(blank=True, max_length=30, null=True)),
                ('HOSPITAL', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.hospitalmodel')),
                ('USER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceBookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('AmbulanceId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.ambulancemodel')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.usermodel')),
            ],
        ),
    ]
