# Generated by Django 5.2.5 on 2025-09-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulancebookingmodel',
            old_name='AmbulanceId',
            new_name='AMBULANCE',
        ),
        migrations.RenameField(
            model_name='ambulancebookingmodel',
            old_name='userid',
            new_name='USER',
        ),
        migrations.RenameField(
            model_name='hospitalmodel',
            old_name='LoGIN',
            new_name='LOGIN',
        ),
    ]
