# Generated by Django 5.2.5 on 2025-09-02 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0002_rename_ambulanceid_ambulancebookingmodel_ambulance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulancebookingmodel',
            name='USER',
        ),
        migrations.AddField(
            model_name='ambulancemodel',
            name='HOSPITAL',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.hospitalmodel'),
        ),
    ]
