# Generated by Django 5.2.5 on 2025-09-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0003_remove_ambulancebookingmodel_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulancemodel',
            name='Vehicle',
        ),
    ]
