# Generated by Django 5.2.5 on 2025-09-02 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0004_remove_ambulancemodel_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulancemodel',
            name='Availability',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='HOSPITAL',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.hospitalmodel'),
        ),
    ]
