# Generated by Django 5.2.5 on 2025-09-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0005_remove_ambulancemodel_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
