# Generated by Django 5.2.5 on 2025-09-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0006_appointmentmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmodel',
            name='Complaint',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='complaintmodel',
            name='Reply',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
