# Generated by Django 5.2.5 on 2025-09-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0007_alter_complaintmodel_complaint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bedmodel',
            old_name='Availability',
            new_name='ward',
        ),
        migrations.RenameField(
            model_name='doctormodel',
            old_name='Contact_no',
            new_name='contact_no',
        ),
    ]
