# Generated by Django 5.2.5 on 2025-09-21 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0008_rename_availability_bedmodel_ward_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bedmodel',
            old_name='RoomNo',
            new_name='count',
        ),
    ]
