# Generated by Django 5.2.5 on 2025-09-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0009_rename_roomno_bedmodel_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyequipmentmodel',
            name='Date',
        ),
        migrations.AddField(
            model_name='pharmacyequipmentmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
