# Generated by Django 5.2.5 on 2025-09-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0010_remove_pharmacyequipmentmodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyequipmentmodel',
            name='Photo',
            field=models.FileField(blank=True, null=True, upload_to='equipment'),
        ),
    ]
