# Generated by Django 5.2.6 on 2025-10-04 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0011_alter_pharmacyequipmentmodel_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True, null=True)),
                ('Issue', models.CharField(blank=True, max_length=50, null=True)),
                ('DoctorName', models.CharField(blank=True, max_length=30, null=True)),
                ('Prescription', models.FileField(blank=True, null=True, upload_to='')),
                ('Status', models.CharField(blank=True, max_length=30, null=True)),
                ('HOSPITAL', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.hospitalmodel')),
            ],
        ),
    ]
