# Generated by Django 5.2.6 on 2025-10-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0012_prescriptionmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionmodel',
            name='DoctorName',
        ),
        migrations.RemoveField(
            model_name='prescriptionmodel',
            name='Issue',
        ),
    ]
