# Generated by Django 5.2.6 on 2025-10-04 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0013_remove_prescriptionmodel_doctorname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmodel',
            name='Description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.usermodel'),
        ),
    ]
