# Generated by Django 5.2.6 on 2025-10-04 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0014_prescriptionmodel_description_prescriptionmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyBookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=30, null=True)),
                ('PRESCRIPTION', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.prescriptionmodel')),
            ],
        ),
    ]
