# Generated by Django 5.2.6 on 2025-10-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0015_pharmacybookingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionmodel',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='prescriptionmodel',
            name='Status',
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='prescription'),
        ),
    ]
