# Generated by Django 5.2.6 on 2025-10-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0016_remove_prescriptionmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmodel',
            name='Prescription',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
