# Generated by Django 5.2.6 on 2025-11-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0017_alter_prescriptionmodel_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='MedicalHistory',
        ),
    ]
