# Generated by Django 5.2.6 on 2025-11-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0018_remove_usermodel_medicalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='Dob',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
