# Generated by Django 5.2.6 on 2025-11-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0019_alter_usermodel_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalmodel',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hospitalmodel',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
