# Generated by Django 5.2.6 on 2025-12-06 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0021_bookdoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancebookingmodel',
            name='USERID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.usermodel'),
        ),
    ]
