# Generated by Django 5.2.6 on 2025-12-07 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0022_ambulancebookingmodel_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alert', models.CharField(blank=True, max_length=100, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('Date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Phone', models.BigIntegerField(blank=True, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Skills', models.TextField(blank=True, null=True)),
                ('Gender', models.TextField(blank=True, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='volunteer/')),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.loginmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.CharField(blank=True, max_length=100, null=True)),
                ('TaskDescription', models.TextField(blank=True, null=True)),
                ('TaskAddress', models.TextField(blank=True, null=True)),
                ('TaskDate', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, default='Assigned', max_length=100, null=True)),
                ('VOLUNTEERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.volunteermodel')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.TextField(blank=True, null=True)),
                ('Rating', models.IntegerField(blank=True, null=True)),
                ('Created', models.DateField(auto_now_add=True)),
                ('VolunteerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.volunteermodel')),
            ],
        ),
    ]
