# Generated by Django 5.2.6 on 2025-12-14 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0023_alertmodel_volunteermodel_taskassignmentmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonationRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bloodgroup', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.usermodel')),
                ('VolunteerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthEmergencyApp.volunteermodel')),
            ],
        ),
    ]
