# Generated by Django 5.2.6 on 2025-12-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0024_blooddonationrequestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteermodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteermodel',
            name='lonngitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
