# Generated by Django 5.2.6 on 2025-12-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0025_volunteermodel_latitude_volunteermodel_lonngitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteermodel',
            old_name='lonngitude',
            new_name='longitude',
        ),
    ]
