# Generated by Django 5.2.6 on 2025-12-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0026_rename_lonngitude_volunteermodel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
