# Generated by Django 5.2.6 on 2025-12-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthEmergencyApp', '0027_usermodel_latitude_usermodel_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmodel',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
